name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al
          git checkout master
          cp ../Prepare_GDoc/docker-compose.yml ./
          docker build -t gdoc/gdoc --network=host .
          docker-compose down
          docker-compose up
